name: deploy

on:
  workflow_call:
  workflow_dispatch:
  push:

concurrency:
  group: deploy-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Setup ci
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Install dependencies and run postinstall
        run: pnpm install

      - name: Build native module
        run: pnpm run build