name: deploy

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      osu:
        description: Github repo to osu!
        required: true
        default: ppy/osu
      ref:
        description: Branch or tag to fetch osu!
        required: true
        default: master

concurrency:
  group: deploy-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  deploy:
    strategy:
      matrix:
        platform: [
          { ci: 'windows-latest', name: 'win32-x64' },
          { ci: 'ubuntu-latest', name: 'linux-x64' }
        ]
    runs-on: ${{ matrix.platform.ci }}
    environment: deploy
    steps:
      - uses: actions/checkout@v6
    
      - name: Fetch osu
        uses: actions/checkout@v6
        with:
          repository: ${{ inputs.osu }}
          ref: ${{ inputs.ref }}
          path: ./lib/vendor

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Apply patches
        run: pnpm run apply-patch:prod

      - name: Build native module
        run: pnpm run build

      - name: Copy artifacts
        run: cp lib/native/dist/binding.node prebuilts/${{ matrix.platform.name }} && cp lib/native/dist/binding.d.ts prebuilts/${{ matrix.platform.name }}

      - name: Pack package
        run: pnpm pack --filter @tosu/pp-${{ matrix.platform.name }} --out prebuilt.tgz

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'tosu-lazer-pp-${{ matrix.platform.name }}'
          path: prebuilt.tgz
