name: publish

on:
  workflow_dispatch:
    inputs:
      execute:
        type: boolean
        description: Actually publish (not dry run)

concurrency:
  group: publish-${{ github.ref_name }}
  cancel-in-progress: true

env:
  NPM_CONFIG_TAG: ${{ github.ref_name == 'main' && 'latest' || github.ref_name }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Setup ci
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Read version
        id: version
        run: echo version=$(pnpm --filter @tosuapp/lazer-calculator exec npm pkg get version | tr -d '"') >> $GITHUB_OUTPUT

      - name: Publish to npm
        run: pnpm publish --filter @tosuapp/lazer-calculator --access public
        env:
          NPM_CONFIG_DRY_RUN: ${{ !inputs.execute && 'true' || 'false' }}
          NPM_CONFIG_PROVENANCE: true
          NPM_CONFIG_PUBLISH_BRANCH: ${{ github.ref_name }}

      - name: Release
        if: ${{ inputs.execute }}
        uses: softprops/action-gh-release@v2
        with:
          name: "v${{ steps.version.outputs.version }}"
          draft: false
          generate_release_notes: true
          make_latest: true
          tag_name: "v${{ steps.version.outputs.version }}"
          target_commitish: "${{ github.ref }}"

  publish-prebuilts:
    strategy:
      matrix:
        platform:
          [
            { ci: "windows-latest", name: "win32-x64" },
            { ci: "ubuntu-latest", name: "linux-x64" },
          ]
    runs-on: ${{ matrix.platform.ci }}
    needs: publish
    permissions:
      id-token: write
    steps:
      - name: Setup ci
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Install dependencies and run postinstall
        run: pnpm install

      - name: Copy artifacts
        run: cp lib/native/dist/binding.node prebuilts/${{ matrix.platform.name }} && cp lib/native/dist/binding.d.ts prebuilts/${{ matrix.platform.name }}
        
      - name: Publish to npm
        run: pnpm publish --filter @tosuapp/lazer-calculator-${{ matrix.platform.name }} --access public
        env:
          NPM_CONFIG_DRY_RUN: ${{ !inputs.execute && 'true' || 'false' }}
          NPM_CONFIG_PROVENANCE: true
          NPM_CONFIG_PUBLISH_BRANCH: ${{ github.ref_name }}
          NPM_CONFIG_GIT_CHECKS: false

  publish-universal-prebuilt:
    runs-on: ubuntu-latest
    needs: publish-prebuilts
    permissions:
      id-token: write
    steps:
      - name: Setup ci
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Publish to npm
        run: pnpm publish --filter @tosuapp/lazer-calculator-prebuilt --access public
        env:
          NPM_CONFIG_DRY_RUN: ${{ !inputs.execute && 'true' || 'false' }}
          NPM_CONFIG_PROVENANCE: true
          NPM_CONFIG_PUBLISH_BRANCH: ${{ github.ref_name }}